version: '3.4'

services:
  identityprovider:
    image: ${DOCKER_REGISTRY-}identityprovider
    build:
      context: .
      dockerfile: IdentityProvider/Dockerfile

  serviceprovider:
    image: ${DOCKER_REGISTRY-}serviceprovider
    build:
      context: .
      dockerfile: ServiceProvider/Dockerfile

